name: tencent_wtn_example_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_icons: ^1.0.0
  flutter_whip:
     git:
         url: https://github.com/cloudwebrtc/flutter-whip.git
         ref: fix-charset-issue-for-tecent-wtn
  random_string: ^2.3.1
  shared_preferences: ^2.0.5
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
